apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 0 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-demo
        image: acr4nt534.azurecr.io/nginx:1.25.4
        securityContext:
          allowPrivilegeEscalation: true
        # resources: 
        #   limits:
        #     cpu: "200m"
        #     memory: "128Mi"
        ports:
        - containerPort: 80
