apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: acr4nt534.azurecr.io/nginx:latest
        securityContext:
          allowPrivilegeEscalation: false # this field should be set to false explicitly