apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-demo
        image: acr4nt534.azurecr.io/nginx:1.25.4
        securityContext:
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 80
